import type { ExploreModalKey } from '@/components/activities/explore/explore-catalog';
import type { IconName } from '@/components/ui/Icon';

export interface ExploreMeta {
  eyebrow: string;
  title: string;
  subtitle: string;
  icon: IconName;
  emoji: string;
}

export const EXPLORE_META: Record<ExploreModalKey, ExploreMeta> = {
  cards: {
    eyebrow: 'PROMPTS',
    title: 'Conversation Cards',
    subtitle: 'Take turns answering — no wrong answers',
    icon: 'cards',
    emoji: '💬',
  },
  games: {
    eyebrow: 'PLAY',
    title: 'Mini Games',
    subtitle: 'Quick rounds for laughs and surprises',
    icon: 'gamepad',
    emoji: '🎲',
  },
  quiz: {
    eyebrow: 'QUIZ',
    title: 'Love Language',
    subtitle: 'Learn how you each feel most loved',
    icon: 'heart',
    emoji: '💞',
  },
  quizLive: {
    eyebrow: 'LIVE',
    title: 'Quiz Live',
    subtitle: 'Pick a topic and compete from your phones',
    icon: 'globe',
    emoji: '🌐',
  },
  bucket: {
    eyebrow: 'DREAM',
    title: 'Bucket List',
    subtitle: 'Collect adventures you want to share',
    icon: 'list',
    emoji: '✈️',
  },
  goals: {
    eyebrow: 'TOGETHER',
    title: 'Shared Goals',
    subtitle: 'Build something as a team',
    icon: 'target',
    emoji: '🎯',
  },
  gratitude: {
    eyebrow: 'TODAY',
    title: 'Gratitude Swap',
    subtitle: 'Three things you appreciated about your partner',
    icon: 'heart',
    emoji: '🙏',
  },
  daily: {
    eyebrow: 'TODAY',
    title: 'Question of the Day',
    subtitle: 'One light prompt — answer together',
    icon: 'journal',
    emoji: '💭',
  },
  trivia: {
    eyebrow: 'PLAY',
    title: 'Couples Trivia',
    subtitle: 'Quick rounds on love, connection & us',
    icon: 'star',
    emoji: '🧠',
  },
  compliment: {
    eyebrow: 'LOVE',
    title: 'Compliment Jar',
    subtitle: 'Drop notes your partner can draw anytime',
    icon: 'gift',
    emoji: '💝',
  },
  twoTruths: {
    eyebrow: 'PLAY',
    title: 'Two Truths & a Lie',
    subtitle: 'Write three statements — one fib',
    icon: 'eye',
    emoji: '🃏',
  },
  truth: {
    eyebrow: 'PLAY',
    title: 'Truth or Dare',
    subtitle: 'Couples-safe truths and dares',
    icon: 'fire',
    emoji: '🔥',
  },
  memory: {
    eyebrow: 'REMEMBER',
    title: 'Memory Quiz',
    subtitle: 'Compare answers about your story',
    icon: 'journal',
    emoji: '🧩',
  },
  playlist: {
    eyebrow: 'MUSIC',
    title: 'Playlist for Two',
    subtitle: 'Pick a song that fits the prompt',
    icon: 'volumeHigh',
    emoji: '🎵',
  },
  thisOrThat: {
    eyebrow: 'QUICK',
    title: 'This or That',
    subtitle: 'Pick one. Compare. Laugh.',
    icon: 'sparkles',
    emoji: '⚡',
  },
  wouldYouRather: {
    eyebrow: 'QUICK',
    title: 'Would You Rather',
    subtitle: 'Hard choices, soft reveals',
    icon: 'question',
    emoji: '🤔',
  },
  whosLikely: {
    eyebrow: 'QUICK',
    title: "Who's More Likely?",
    subtitle: 'Point fingers, then reveal together',
    icon: 'eye',
    emoji: '👀',
  },
  loveQuiz: {
    eyebrow: 'QUIZ',
    title: 'How well do you know me?',
    subtitle: 'One answers — the other guesses',
    icon: 'heart',
    emoji: '💕',
  },
  neverHaveI: {
    eyebrow: 'PLAY',
    title: 'Never Have I Ever',
    subtitle: 'Couples-safe confessions',
    icon: 'fire',
    emoji: '🙈',
  },
  finishSentence: {
    eyebrow: 'PROMPTS',
    title: 'Finish the Sentence',
    subtitle: 'Complete the line out loud',
    icon: 'journal',
    emoji: '✍️',
  },
  emojiStory: {
    eyebrow: 'PLAY',
    title: 'Emoji Story',
    subtitle: 'Guess the night from emojis',
    icon: 'sparkles',
    emoji: '🧩',
  },
  appreciation: {
    eyebrow: 'PROMPTS',
    title: 'Appreciation Cards',
    subtitle: 'One grateful note, right now',
    icon: 'heart',
    emoji: '💌',
  },
  thirtySix: {
    eyebrow: 'DEEP',
    title: '36 Questions',
    subtitle: 'Unlock one at a time',
    icon: 'list',
    emoji: '📖',
  },
  weekChallenge: {
    eyebrow: 'CHALLENGE',
    title: '7-Day Connection',
    subtitle: 'Tiny daily habits, big payoff',
    icon: 'target',
    emoji: '🔥',
  },
  dateNight: {
    eyebrow: 'CHALLENGE',
    title: 'Date Night Challenge',
    subtitle: 'Complete together this week',
    icon: 'calendar',
    emoji: '🌙',
  },
  fortuneWheel: {
    eyebrow: 'PLAY',
    title: 'Love Fortune Wheel',
    subtitle: 'Spin for a tiny dare',
    icon: 'spark',
    emoji: '🎡',
  },
  dateGenerator: {
    eyebrow: 'REAL LIFE',
    title: 'Random Date Generator',
    subtitle: 'Shake up your next night out',
    icon: 'compass',
    emoji: '📍',
  },
  drawTogether: {
    eyebrow: 'CREATIVE',
    title: 'Draw Together',
    subtitle: 'Same prompt. Reveal together.',
    icon: 'image',
    emoji: '✏️',
  },
  compatibility: {
    eyebrow: 'QUIZ',
    title: 'Compatibility',
    subtitle: 'See where you align',
    icon: 'sparkles',
    emoji: '🧭',
  },
  personality: {
    eyebrow: 'QUIZ',
    title: 'Personality',
    subtitle: 'Your vibe, side by side',
    icon: 'user',
    emoji: '🪞',
  },
  attachment: {
    eyebrow: 'QUIZ',
    title: 'Attachment Style',
    subtitle: 'How you need to feel close',
    icon: 'people',
    emoji: '🫶',
  },
  guessAnswer: {
    eyebrow: 'QUICK',
    title: 'Guess My Answer',
    subtitle: 'They type. You guess.',
    icon: 'chat',
    emoji: '🎯',
  },
};
