import { StyleSheet } from 'react-native';

export const exploreStyles = StyleSheet.create({
  stack: { gap: 14 },
  tabs: { gap: 8, paddingBottom: 2 },
  tab: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: StyleSheet.hairlineWidth,
  },
  tabText: { fontSize: 13, fontWeight: '700' },
  promptCard: {
    borderRadius: 22,
    padding: 24,
    minHeight: 220,
    justifyContent: 'center',
    gap: 8,
  },
  quoteMark: { color: 'rgba(255,255,255,0.45)', fontSize: 48, fontWeight: '800', lineHeight: 48 },
  promptText: { color: '#fff', fontSize: 24, fontWeight: '700', lineHeight: 32 },
  promptHint: { color: 'rgba(255,255,255,0.75)', fontSize: 13, fontWeight: '600', marginTop: 8 },
  gameTile: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    padding: 16,
    borderRadius: 18,
    borderWidth: StyleSheet.hairlineWidth,
    overflow: 'hidden',
  },
  gameTileEmoji: { fontSize: 28, width: 36, textAlign: 'center' },
  gameTileAccent: { position: 'absolute', left: 0, top: 0, bottom: 0, width: 4, borderTopLeftRadius: 18, borderBottomLeftRadius: 18 },
  gameTileBody: { flex: 1, gap: 2 },
  gameTileTitle: { fontSize: 16, fontWeight: '800' },
  gameTileDesc: { fontSize: 13, lineHeight: 18 },
  backLink: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  backLinkText: { fontWeight: '700', fontSize: 14 },
  roundHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  roundGame: { fontSize: 18, fontWeight: '800' },
  roundNum: { fontSize: 12, fontWeight: '700', letterSpacing: 0.5 },
  gamePlayCard: { borderRadius: 22, padding: 24, minHeight: 200, gap: 14, justifyContent: 'center' },
  gamePrompt: { color: '#fff', fontSize: 22, fontWeight: '800', lineHeight: 30 },
  optionsCol: { gap: 10 },
  optionPill: { backgroundColor: 'rgba(255,255,255,0.18)', borderRadius: 14, padding: 14 },
  optionText: { color: '#fff', fontSize: 16, fontWeight: '600', textAlign: 'center' },
  gameAnswer: { color: '#fff', fontSize: 20, fontWeight: '800', textAlign: 'center', marginTop: 4 },
  progressWrap: { gap: 6 },
  progressTrack: { height: 6, borderRadius: 3, overflow: 'hidden' },
  progressFill: { height: 6, borderRadius: 3 },
  progressLabel: { fontSize: 12, fontWeight: '600' },
  quizBlock: { borderRadius: 18, borderWidth: StyleSheet.hairlineWidth, padding: 16, gap: 10 },
  quizNum: { fontSize: 11, fontWeight: '800', letterSpacing: 0.8 },
  quizQ: { fontSize: 16, fontWeight: '700', lineHeight: 22 },
  quizOptions: { gap: 8, marginTop: 4 },
  quizOption: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 14,
    borderRadius: 14,
    borderWidth: 1.5,
    gap: 10,
  },
  quizOptionText: { flex: 1, fontSize: 14, lineHeight: 20 },
  resultCard: { borderRadius: 22, padding: 28, alignItems: 'center', gap: 8 },
  resultEyebrow: { color: 'rgba(255,255,255,0.8)', fontSize: 11, fontWeight: '800', letterSpacing: 1, marginTop: 8 },
  resultTitle: { color: '#fff', fontSize: 26, fontWeight: '800', textAlign: 'center' },
  resultDesc: { color: 'rgba(255,255,255,0.92)', fontSize: 15, lineHeight: 22, textAlign: 'center', marginTop: 4 },
  resultShare: { fontSize: 13, textAlign: 'center', lineHeight: 18 },
  inputCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 8,
    paddingLeft: 14,
    borderRadius: 16,
    borderWidth: StyleSheet.hairlineWidth,
  },
  input: { flex: 1, fontSize: 15, paddingVertical: 10 },
  inputBtn: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center' },
  emptyCard: {
    alignItems: 'center',
    padding: 28,
    borderRadius: 18,
    borderWidth: StyleSheet.hairlineWidth,
    gap: 6,
  },
  emptyEmoji: { fontSize: 40, marginBottom: 4 },
  emptyTitle: { fontSize: 17, fontWeight: '800' },
  emptySub: { fontSize: 13, lineHeight: 19, textAlign: 'center', maxWidth: 260 },
  listRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 14,
    borderRadius: 14,
    borderWidth: StyleSheet.hairlineWidth,
  },
  check: { width: 26, height: 26, borderRadius: 8, borderWidth: 2, alignItems: 'center', justifyContent: 'center' },
  listText: { flex: 1, fontSize: 15, fontWeight: '600', lineHeight: 20 },
  listTextDone: { textDecorationLine: 'line-through', opacity: 0.55 },
  goalCard: { padding: 16, borderRadius: 18, borderWidth: StyleSheet.hairlineWidth, gap: 12 },
  goalTop: { flexDirection: 'row', alignItems: 'flex-start', gap: 10 },
  goalTitle: { flex: 1, fontSize: 16, fontWeight: '800', lineHeight: 21 },
  goalPct: { fontSize: 18, fontWeight: '800' },
  goalTrack: { height: 10, borderRadius: 5, overflow: 'hidden' },
  goalFill: { height: 10, borderRadius: 5 },
  goalBtns: { flexDirection: 'row', gap: 10 },
  goalBtn: { flex: 1, paddingVertical: 10, borderRadius: 12, borderWidth: 1.5, alignItems: 'center' },
  dateCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 16,
    borderRadius: 18,
    borderWidth: StyleSheet.hairlineWidth,
  },
  dateEmoji: { fontSize: 32, width: 40, textAlign: 'center' },
  dateBody: { flex: 1, gap: 3 },
  dateTitle: { fontSize: 16, fontWeight: '800' },
  dateDesc: { fontSize: 13, lineHeight: 18 },
  dateMeta: { fontSize: 11, fontWeight: '700', textTransform: 'capitalize', marginTop: 4 },
  dateAdd: { width: 44, height: 44, borderRadius: 22, borderWidth: 1.5, alignItems: 'center', justifyContent: 'center' },
  hintText: { fontSize: 14, lineHeight: 20 },
  hintCard: {
    padding: 16,
    borderRadius: 16,
    borderWidth: StyleSheet.hairlineWidth,
    gap: 4,
  },
  hintCardLabel: { fontSize: 12, fontWeight: '600' },
  hintCardValue: { fontSize: 18, fontWeight: '800' },
  moodGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  moodChip: {
    width: '30%',
    flexGrow: 1,
    minWidth: 96,
    alignItems: 'center',
    paddingVertical: 12,
    borderRadius: 14,
    borderWidth: StyleSheet.hairlineWidth,
    gap: 4,
  },
  moodChipEmoji: { fontSize: 26 },
  moodChipLabel: { fontSize: 11, fontWeight: '700' },
  gratitudeRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    padding: 14,
    borderRadius: 16,
    borderWidth: StyleSheet.hairlineWidth,
  },
  gratitudeNum: { fontSize: 16, fontWeight: '800', width: 20, marginTop: 2 },
  gratitudeInput: { flex: 1, fontSize: 15, lineHeight: 21, minHeight: 44 },
  dailyCard: { borderRadius: 22, padding: 24, minHeight: 180, justifyContent: 'center', gap: 10 },
  dailyLabel: { color: 'rgba(255,255,255,0.8)', fontSize: 11, fontWeight: '800', letterSpacing: 1 },
  dailyQuestion: { color: '#fff', fontSize: 22, fontWeight: '800', lineHeight: 30 },
  dailyHint: { color: 'rgba(255,255,255,0.75)', fontSize: 13, marginTop: 6 },
});
